apiVersion: samples.knative.dev/v1alpha1
kind: SimpleDeployment
metadata:
  generateName: example-
  annotations:
    pipelinesAsCode.tekton.dev/repoName: repo-one
spec:
  image: gcr.io/knative-samples/helloworld-go
  replicas: 2
